[workspace]
authors = ["Noha El-Haj <elhajn02@gmail.com>"]
channels = ["conda-forge"]
name = "BINF5507-Materials"
platforms = ["osx-arm64", "win-64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pip = ">=25.1.1,<26"
pandas = ">=2.3.0,<3"
numpy = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
scikit-learn = ">=1.6.1,<2"
scikit-survival = ">=0.24.1,<0.25"
lifelines = ">=0.30.0,<0.31"
statsmodels = ">=0.14.4,<0.15"
